drop table if exists "Stock" cascade;
drop table if exists "Log" cascade;

create table "Stock" (
  id int generated by default as identity primary key,
  name text unique not null,
  ticker text unique not null
);

create table "Log" (
  id int generated by default as identity primary key,
  stock_id int references "Stock" (id),
  amount float not null,
  quarter integer not null
);